version: '3'
services:
  web:
    build: .
    ports:
      - "8501:80"
    depends_on:
      - redis
    restart: always
    volumes:
      - ./app:/app
  redis:
    image: "redis:alpine"
    restart: always